name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry self add poetry-plugin-lambda-build poetry-plugin-export

      - name: Install xc
        uses: joerdav/setup-xc@v0.0.3

      - name: Run tests
        run: xc unit

      - name: Run linting
        run: xc lint

      - name: Integration tests
        env:
          LOCALSTACK_INTERNAL_DYNAMODB_ENDPOINT: http://localstack:4566/
        run: xc integration
