name: Continuous Integration

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry self add poetry-plugin-lambda-build poetry-plugin-export

      - name: Unit tests
        uses: joerdav/setup-xc@v0.0.3
        id: unit

      - name: Run linting
        uses: joerdav/setup-xc@v0.0.3
        id: lint

      - name: Integration tests
        uses: joerdav/setup-xc@v0.0.3
        id: integration
